trigger:
- main
- experimental

pool: Hill Infrastructure

steps:
- script: |
    cd Games\Skylight
    echo Executing tsc...
    tsc -b
    echo Done.
  displayName: 'TypeScript Build'
  
- publish: 'Games\Skylight\index.html'
  artifact: skylight
  displayName: Skylight
