trigger:
- main
- experimental

pool: Hill Infrastructure

steps:
- script: |
    cd Games\Skylight
    npm install typescript
    tsc -b
  displayName: 'TypeScript Build'
  
- publish: 'Games\Skylight\*.js'
  artifact: skylight
  displayName: Skylight

