trigger:
- main
- experimental

pool: Hill Infrastructure

steps:
- script: |
    echo Installing tsc...
    npm install -g typescript
    echo Executing tsc...
    tsc -b
    echo Done.
  displayName: 'TypeScript Build'
  workingDirectory: Games\Skylight
  
- publish: 'Games\Skylight\index.html'
  artifact: skylight
  displayName: Skylight
